from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any


def format_percent(value: float | None, digits: int = 2) -> str:
    if value is None:
        return "n/a"
    return f"{value * 100:.{digits}f}%"


def format_float(value: float | None, digits: int = 4) -> str:
    if value is None:
        return "n/a"
    return f"{value:.{digits}f}"


def _markdown_table(rows: list[dict[str, Any]], columns: list[str]) -> str:
    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join(["---"] * len(columns)) + " |"
    body = [
        "| " + " | ".join(str(row.get(col, "")) for col in columns) + " |"
        for row in rows
    ]

    return "\n".join([header, separator] + body)


def build_signal_markdown(payload: dict[str, Any]) -> str:
    setup = payload["setup"]
    signal = payload["signal"]
    data = payload["data"]
    evidence = payload.get("research_evidence", {})
    top_features = payload.get("top_model_features", [])

    setup_rows = [
        {"Metric": "Candidate", "Value": payload["candidate_name"]},
        {"Metric": "Feature Set", "Value": setup["feature_set"]},
        {"Metric": "LOOKAHEAD", "Value": setup["lookahead"]},
        {"Metric": "TP", "Value": format_percent(setup["tp"])},
        {"Metric": "SL", "Value": format_percent(setup["sl"])},
        {"Metric": "Threshold", "Value": format_percent(setup["threshold"])},
        {
            "Metric": "Round-trip Cost",
            "Value": format_percent(setup.get("round_trip_cost")),
        },
        {
            "Metric": "Breakeven Precision",
            "Value": format_percent(signal.get("breakeven_precision")),
        },
        {
            "Metric": "Min Required Precision",
            "Value": format_percent(signal.get("min_required_precision")),
        },
    ]

    signal_rows = [
        {"Metric": "Latest Feature Date", "Value": data["latest_feature_date"]},
        {"Metric": "Latest Data Date", "Value": data["latest_data_date"]},
        {"Metric": "Data Lag Days", "Value": data["data_lag_days"]},
        {"Metric": "Latest Close", "Value": format_float(data.get("latest_close"), 2)},
        {"Metric": "Training Rows", "Value": data["training_rows"]},
        {"Metric": "Predicted Probability", "Value": format_percent(signal["probability"])},
        {"Metric": "Signal", "Value": signal["action"]},
        {"Metric": "Reason", "Value": signal["reason"]},
    ]

    evidence_rows = [
        {"Metric": "Frozen Pass Periods", "Value": evidence.get("pass_periods", "n/a")},
        {"Metric": "Frozen Min Edge", "Value": format_percent(evidence.get("min_edge"))},
        {"Metric": "Frozen Avg Return", "Value": format_percent(evidence.get("avg_return"))},
        {"Metric": "Cost Stress", "Value": format_percent(evidence.get("round_trip_cost"))},
    ]

    lines = [
        f"# {payload['ticker']} {payload['profile']} Latest Signal",
        "",
        f"**Action:** `{signal['action']}`",
        "",
        f"**Probability:** `{format_percent(signal['probability'])}`",
        "",
        "## Setup",
        "",
        _markdown_table(setup_rows, ["Metric", "Value"]),
        "",
        "## Latest signal",
        "",
        _markdown_table(signal_rows, ["Metric", "Value"]),
        "",
        "## Research evidence",
        "",
        _markdown_table(evidence_rows, ["Metric", "Value"]),
        "",
    ]

    if top_features:
        feature_rows = [
            {
                "Rank": item["rank"],
                "Feature": item["feature"],
                "Importance": format_float(item["importance"], 6),
            }
            for item in top_features[:10]
        ]

        lines.extend(
            [
                "## Top model features",
                "",
                _markdown_table(feature_rows, ["Rank", "Feature", "Importance"]),
                "",
            ]
        )

    lines.extend(
        [
            "## Notes",
            "",
            "- This report is generated by the research signal runner.",
            "- This is not investment advice and should not be used without independent risk controls.",
            "",
            "## Source",
            "",
            f"- Generated at: `{payload['generated_at']}`",
            f"- Script version: `{payload['script_version']}`",
            "",
        ]
    )

    return "\n".join(lines)


def write_signal_outputs(
    payload: dict[str, Any],
    output_dir: Path,
) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)

    stem = f"{payload['ticker']}_{payload['profile']}_latest_signal"

    md_path = output_dir / f"{stem}.md"
    json_path = output_dir / f"{stem}.json"

    md_path.write_text(build_signal_markdown(payload), encoding="utf-8")
    json_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    return md_path, json_path


def now_iso() -> str:
    return datetime.now().isoformat(timespec="seconds")
